name: Publish release

on:
  workflow_dispatch:
    inputs:
      releaseType:
        type: choice
        required: true
        description: "Release type"
        default: "patch"
        options:
          - patch
          - minor
          - major
      releaseBody:
        type: string
        required: true
        description: "Release description"

jobs:
  publish:
    name: Publish to package registry
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout branch
        uses: actions/checkout@v6

      - name: Build package
        id: build
        uses: ./.github/actions/build-package
        with:
          publish_type: release
          version_type: ${{ inputs.releaseType }}

      - name: Publish package
        id: publish
        shell: bash
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Push version commit and tag
        if: steps.publish.outcome == 'success'
        shell: bash
        run: git push --follow-tags

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.build.outputs.version_tag }}
          body: ${{ inputs.releaseBody }}